server:
  port: 8080
  servlet:
    context-path: /api

spring:
  application:
    name: quick-multimodule

  # Database Configuration (H2 for demo purposes)
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:

  # H2 Console (for development/testing)
  h2:
    console:
      enabled: true
      path: /h2-console

  # JDBC Configuration
  sql:
    init:
      mode: always
      platform: h2

# Logging Configuration
logging:
  level:
    com.example.hello: DEBUG
    org.springframework.jdbc: DEBUG
    org.springframework.data.jdbc: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"

# Management endpoints
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always